export const MODULE_LABELS: Record<string, string> = {
  auth: "Autenticación",
  users: "Usuarios",
  customers: "Clientes",
  suppliers: "Proveedores",
  transactions: "Transacciones",
  roles: "Roles",
  expense_categories: "Categoria Gastos",
  expenses: "Gastos",
  permissions: "Permisos",
  banks: "Bancos",
  investments: "Inversiones",
  products: "Productos",
  purchases: "Compras",
  loans: "Creditos",
  purchase_payments: "Pago compras",
  sale_payments: "Pago ventas",
  statuses: "Estados",
  sales: "Ventas",
  invoices: "Facturas",
  reports: "Reportes",
  dashboard: "Dashboard",
};

export const ACTION_LABELS: Record<string, string> = {
  view: "ver",
  read: "leer",
  create: "crear",
  update: "actualizar",
  delete: "eliminar",
  export: "exportar",
  import: "importar",
  approve: "aprobar",
  cancel: "anular",
  update_balance: "actualizar saldo",
  update_amount: "actualizar monto",
  product_read: "ver productos",
  product_upload: "subir productos",
  purchase_read: "ver compras",
  sold_in_range: "ventas en rango",
};
